handlers=java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=com.clickhouse.jdbcbridge.core.JsonLogFormatter

.level=INFO

# Completely disable Vert.x and Netty logs (including shaded packages)
io.vertx.level=OFF
io.netty.level=OFF
com.clickhouse.jdbcbridge.internal.vertx.level=OFF
com.clickhouse.jdbcbridge.internal.netty.level=OFF
