handlers=java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=[%1$tF %1$tT] [%4$-7s] %5$s%6$s%n

.level=INFO

# Completely disable Vert.x and Netty logs (including shaded packages)
io.vertx.level=OFF
io.netty.level=OFF
com.clickhouse.jdbcbridge.internal.vertx.level=OFF
com.clickhouse.jdbcbridge.internal.netty.level=OFF
