name: Release

on:
  workflow_dispatch:
    inputs:
      major:
        description: "Major version"
        required: true
        default: "2"
      minor:
        description: "Minor version"
        required: false
        default: "1"
      patch:
        description: "Patch"
        required: false
        default: "0"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - run: sed -i -e 's|^\(    <version>\).*\(</version>\)$|\1${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}\2|' pom.xml
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_profiles: release
          maven_args: -Drevision=${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }} --batch-mode
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.SONATYPE_USER }}
          nexus_password: ${{ secrets.SONATYPE_PASSWD }}
      
      - name: Create Pre-release on Github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}"
          name: "Release v${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}"
          prerelease: true
          generate_release_notes: true
          files: |
            LICENSE
            NOTICE
            target/clickhouse*.jar
            target/*.deb
            target/**/*.rpm

  publish:
    name: "Publish Docker Images"
    needs: pre-release
    uses: ./.github/workflows/docker-publish.yml
    with:
      major: ${{ github.event.inputs.major }}
      minor: ${{ github.event.inputs.minor }}
      patch: ${{ github.event.inputs.patch }}
    secrets: inherit
